name: Test2
on: [workflow_dispatch]
jobs:
  Test2:
    runs-on: ubuntu-latest
    steps:
      - name: "1"
        run: |
          echo "::notice title=[Test](https://github.com/JohannesK71083/actions_test/releases/tag/untagged-49c85d6c3f8c7746149d)"
