name: Test
run-name: ${{ github.actor }} is testing
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: "JohannesK71083/actions_compose_test@main"
      - run: |
          TEST=1
          echo $TEST
          echo "TEST=$TEST" >> "$GITHUB_ENV"
      - run: "echo $TEST"
 
