name: create release
run-name: ${{ github.actor }} is testing
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "release type"
        required: true
        type: choice
        options:
          - major version
          - minor version
          - no new version (prerelease required)
        default: "no new version (prerelease required)"
      prerelease:
        required: true
        type: boolean
        default: true
        
jobs:
  releaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: "JohannesK71083/actions_compose_test@main"
