name: Test Pyinstaller
on:
  workflow_dispatch

jobs:
  Pyinstaller:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: execute pyinstaller_action
        uses: "JohannesK71083/pyinstaller_action@main"
        with:
          python-requirements-file-path: "repo/requirements.txt"
          input-file-path: "repo\\test.py"
          onefile: "true"
          no-console: "false"
      - name: Upload output PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: output/test.exe