name: Test Visio to PDF
on:
  workflow_dispatch:
    inputs:
      visio_to_pdf_action_show_logs:
        required: true
        type: boolean
        default: false

jobs:
  Visio_to_PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          repository: "JohannesK71083/visio_to_pdf_action"
          ssh-key: ${{ secrets.VISIO_TO_PDF_ACTION_SSH_KEY }}
          path: visio_to_pdf_action
      - name: Visio_to_PDF
        uses: "./visio_to_pdf_action"
        with:
          input-file-path: "repo/test.vsdx"
          output-file-path: "test.pdf"
          show-logs: ${{ inputs.visio_to_pdf_action_show_logs }}
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.pdf