name: create release
run-name: create new release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "release type"
        required: true
        type: choice
        options:
          - major version
          - minor version
          - no new version (prerelease required)
        default: "no new version (prerelease required)"
      prerelease:
        required: true
        type: boolean
        default: true
        
jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: "JohannesK71083/actions_compose_test@main"
        with:
          mode: ${{ inputs.release-type == 'major version' && 'major' ||  inputs.release-type == 'minor version' && 'minor' ||  inputs.release-type == 'no new version (prerelease required)' && 'pre' || 'else' }}
          prerelease: ${{ inputs.prerelease }}
          tag_format: "V{Maj}.{Min}[_pre-{Pre}]"
          reuse_old_body: ${{ true }}
