name: Test Visio to PDF
on: [workflow_dispatch]
jobs:
  Visio_to_PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Visio_to_PDF
        uses: "JohannesK71083/visio_to_pdf_action@main"
        with:
          input-file-path: "repo/test.vsdx"
          output-file-path: "test.pdf"
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.pdf