name: Test
run-name: ${{ github.actor }} is testing
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "release type"
        required: true
        type: choice
        options:
          - major version
          - minor version
          - no new version
        default: ""
      prerelease:
        required: true
        type: boolean
        
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: "JohannesK71083/actions_compose_test@main"
      - run: |
          TEST=1
          echo $TEST
          echo "TEST=$TEST" >> "$GITHUB_ENV"
          echo $TEST2
        env:
          TEST2: ${{ inputs.version }}
      - run: "echo $TEST"
  JOB-2:
    runs-on: ubuntu-latest
    steps:
      - run: "echo $TEST"
 
